### ISSUE TITLE
"Media has no indexed available formats"

### ISSUE THREAD

**Issue by mikiway-git** [meeb/tubesync#380]
Apparently I can't download a lot of video from this channel and i can't find how to solve this : https://www.youtube.com/channel/UC43CzJJQybW1VtvfWCPrd5Q
<img width="922" alt="Capture d’écran 2023-05-22 à 19 39 59" src="https://github.com/meeb/tubesync/assets/129160517/017931f8-38c1-4d41-9adb-6f569496fd18">

Here is skipped videos page : 

<img width="922" alt="Capture d’écran 2023-05-22 à 19 40 58" src="https://github.com/meeb/tubesync/assets/129160517/f42d7e10-65b8-4646-a2ea-dcc44317cc84">

They all have the "no index" status. Here is an exemple of video with the error : https://www.youtube.com/watch?v=tTnw5q6FgTQ

<img width="922" alt="Capture d’écran 2023-05-22 à 19 41 31" src="https://github.com/meeb/tubesync/assets/129160517/91e0beab-f9ae-4b31-a01e-6550bdb645d6">

I tried deleting the channel to re-download, updating the app, reseted tasks with command, same result . I'm using this version of Tubesync : 

<img width="923" alt="Capture d’écran 2023-05-22 à 19 57 43" src="https://github.com/meeb/tubesync/assets/129160517/5d14ce22-15e0-417c-9998-c3efed974a78">

Thank you for this great app.

**Comment by meeb** [comment]
Is there anything in the container logs? This is likely to be an issue with your containers ability to write the metadata to disk. Are you using MySQL as the database?

**Comment by meeb** [comment]
OK, are you absolutely sure you created the tubesync database in MySQL with the `utf8mb4` character set?

**Comment by mikiway-git** [comment]
It seems to be good.

<img width="1018" alt="Capture d’écran 2023-05-23 à 18 04 21" src="https://github.com/meeb/tubesync/assets/129160517/96581751-a729-4b4d-9ebd-054f32364d2d">

<img width="514" alt="Capture d’écran 2023-05-23 à 18 06 43" src="https://github.com/meeb/tubesync/assets/129160517/c48b6b42-958c-411c-b9b1-167920a1d088">

**Comment by meeb** [comment]
No idea then, the error implies the container loses the connection to the MySQL server for some reason. Typically with content with unicode chars in the video titles when using a MySQL database the issue is the database or table or field is not set to the utf8mb4 charset as Python uses 4 byte unicode chars and MySQL defaults to 3 byte unicode chars so the INSERT fails. In your cause the "MySQL server has gone away" means "The MySQL server closed the connection or the connection timed out". See https://dev.mysql.com/doc/refman/8.0/en/gone-away.html

**Comment by mikiway-git** [comment]
Hi, here is some news. Since MariaDB is not able of utf8mb4_0900_ai_ci, I converted the database from utf8_general_ci  to utf8mb4_unicode_ci and also tried utf8mb4_unicode_520_ci without success (same errors). I'm now using a postgresql database and the problem is solved.

**Comment by meeb** [comment]
Interesting, thanks for the update. I don't use MySQL or any of its derivatives myself, but MySQL does have a pretty long history of not handing long term connections well. There's some hacks in tubesync that attempt to work around these issues like:

https://github.com/meeb/tubesync/blob/main/tubesync/tubesync/dbutils.py

but evidently from your initial issue these are not fully solved. Good to hear you've fixed it though! For anyone else to stumbles over this issue the general advice is use SQLite or Postgres, it's a lot less hassle!
