### ISSUE TITLE
Download fails for videos with "%" in the title

### ISSUE THREAD

**Issue by awawis** [meeb/tubesync#55]
I am getting an error when trying to download this video: https://www.youtube.com/watch?v=1vPOFZpLoRU

The video title is "_42% of you just wing it. Building a new pantry storage cabinet._" and I am using this as the filename format: _{source_full} - {title_full} - {playlist_title} E{playlist_index} - {yyyymmdd}.{ext}_

I believe it is failing because there is an illegal character (%) in the title. Can illegal characters be replaced with something else when saving? 

Running in Docker on Unraid 6.9rc2

![image](https://user-images.githubusercontent.com/22629881/108304797-a2abd700-715d-11eb-819f-de19891a65d4.png)

Also - thanks again for making TubeSync!

**Comment by meeb** [comment]
Good catch, thanks. Fixed in `:latest`. % are now scrubbed in video titles before being used in filenames when `title_full` is used.

**Comment by awawis** [comment]
I've just run into this with another video that uses emojis in the title: https://www.youtube.com/watch?v=UZN-QLQc8gw

Title: 🚀REVISED TO THE MOON! $2,000 DUAL LANDS COMING🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

Looking at your [commit 895bfe6f879a638cdd69b75163bc10ec15ac7fdf](https://github.com/meeb/tubesync/commit/895bfe6f879a638cdd69b75163bc10ec15ac7fdf), this might be a bit trickier to solve.

Here are a couple leads I found on Stackoverflow for dealing with Emojis: 

https://stackoverflow.com/questions/61757407/how-to-ignore-punctuation-in-between-words-using-word-tokenize-in-nltk/61758471#61758471

https://stackoverflow.com/questions/33404752/removing-emojis-from-a-string-in-python/50602709#50602709

**Comment by meeb** [comment]
Technically emojis are allowed with file systems that support UTF-8:

```bash
$ echo test > 🚀🚀
$ cat 🚀🚀
test
```

But I can see that could be annoying. Stripping emotes isn't too much work so I'll consider it.

**Comment by awawis** [comment]
Perhaps it should work, but I am still getting an error:

![image](https://user-images.githubusercontent.com/22629881/108406511-62893a80-71d7-11eb-8239-2c4021aa59f3.png)

**Comment by meeb** [comment]
You can always use `{title}` not `{title_full}` for now which will be a slug-ised and all file systems safe title to use for filenames if that helps. I'll look into possibly filtering emotes in the future though.

**Comment by meeb** [comment]
Looks like unRAID is indeed a bit weird with extended unicode chars in filenames after a quick search, probably because it attempts to keep things simple and allow maps to SMB shares etc. Advice is to use `{title}` for now as per previous comment.

**Comment by awawis** [comment]
Thanks, I'll use that workaround for now
